// Generated by gencpp from file demo_comm_pkg/Server_01Response.msg
// DO NOT EDIT!


#ifndef DEMO_COMM_PKG_MESSAGE_SERVER_01RESPONSE_H
#define DEMO_COMM_PKG_MESSAGE_SERVER_01RESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_comm_pkg
{
template <class ContainerAllocator>
struct Server_01Response_
{
  typedef Server_01Response_<ContainerAllocator> Type;

  Server_01Response_()
    : response_01(0)  {
    }
  Server_01Response_(const ContainerAllocator& _alloc)
    : response_01(0)  {
  (void)_alloc;
    }



   typedef int32_t _response_01_type;
  _response_01_type response_01;





  typedef boost::shared_ptr< ::demo_comm_pkg::Server_01Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_comm_pkg::Server_01Response_<ContainerAllocator> const> ConstPtr;

}; // struct Server_01Response_

typedef ::demo_comm_pkg::Server_01Response_<std::allocator<void> > Server_01Response;

typedef boost::shared_ptr< ::demo_comm_pkg::Server_01Response > Server_01ResponsePtr;
typedef boost::shared_ptr< ::demo_comm_pkg::Server_01Response const> Server_01ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_comm_pkg::Server_01Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_comm_pkg::Server_01Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_comm_pkg::Server_01Response_<ContainerAllocator1> & lhs, const ::demo_comm_pkg::Server_01Response_<ContainerAllocator2> & rhs)
{
  return lhs.response_01 == rhs.response_01;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_comm_pkg::Server_01Response_<ContainerAllocator1> & lhs, const ::demo_comm_pkg::Server_01Response_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_comm_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_comm_pkg::Server_01Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_comm_pkg::Server_01Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_comm_pkg::Server_01Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_comm_pkg::Server_01Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_comm_pkg::Server_01Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_comm_pkg::Server_01Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_comm_pkg::Server_01Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7395311b7148d413a144ccaf24313d51";
  }

  static const char* value(const ::demo_comm_pkg::Server_01Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7395311b7148d413ULL;
  static const uint64_t static_value2 = 0xa144ccaf24313d51ULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_comm_pkg::Server_01Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_comm_pkg/Server_01Response";
  }

  static const char* value(const ::demo_comm_pkg::Server_01Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_comm_pkg::Server_01Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#自定义服务器响应传输的数据\n"
"int32 response_01\n"
;
  }

  static const char* value(const ::demo_comm_pkg::Server_01Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_comm_pkg::Server_01Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response_01);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Server_01Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_comm_pkg::Server_01Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_comm_pkg::Server_01Response_<ContainerAllocator>& v)
  {
    s << indent << "response_01: ";
    Printer<int32_t>::stream(s, indent + "  ", v.response_01);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_COMM_PKG_MESSAGE_SERVER_01RESPONSE_H
